### ISSUE TITLE
gitStream check is failing - The job running on runner Hosted Agent has exceeded the maximum execution time of 5 minutes.

### ISSUE THREAD

**Issue by AnkurAgarwal-ST** [linear-b/gitstream#10]
**Describe the bug**

In one of the PR, gitStream seems to be stuck. We tried even with multiple commits so that the check could restart, but there was still no success & it remains in "In progress — This check has started...." state
PR URL - https://github.com/Hodes-Inc/XCloud.JEE6.CoreAPIs/pull/7201

**To Reproduce**

Raise a PR and wait for the gitstream checks to finish.
Notice that the gitStream status is shown as "In progress for hours" in the pr, but if we check inside Actions list of the repo it will shown as failed.
The actions displays the error as - _"The job running on runner Hosted Agent has exceeded the maximum execution time of 5 minutes."_

**Expected behavior**

The gitstream should not be failed with message _"The job running on runner Hosted Agent has exceeded the maximum execution time of 5 minutes."_
The gitStream checks should be executed and get finished in a reasonable time.
If the gitstream check has failed, it should be reflected in the PR status check sections as well.

**Screenshots**

![image](https://user-images.githubusercontent.com/89902473/212637648-9df3df31-170f-4db8-9e59-a1effc6fbb00.png)
![image](https://user-images.githubusercontent.com/89902473/212637739-bbfd356d-feb3-4b1e-83c4-4da7819b853a.png)
![image](https://user-images.githubusercontent.com/89902473/212639341-0b6a6b1d-0bbc-4604-b32f-10ac5b8c4c2d.png)

**Additional context**

This issue has been noticed for this one particular pr only.

**Comment by vim-zz** [comment]
We are looking at it @AnkurAgarwal-ST

**Comment by vim-zz** [comment]
@AnkurAgarwal-ST we found the issue, it happens because you manually removed a label that was genereted automatically and this got the action get to an undefined behavior. The issue was fixed, please do another commit to the PR to get it back to normal state.

**Comment by AnkurAgarwal-ST** [comment]
Hi @vim-zz,
I don't think anyone removed a label auto-generated by gitStream.
gitStream has never been able to run once on the reported pr, so it cannot generate any label.
I also checked the activity on the pr and I can't find any action of adding or removing label either by a team member or by gitstream.
We have merged that pr now so we cannot test anymore on that pr.

Please correct me if I am missing something.

**Comment by vim-zz** [comment]
We identifed a state that results with undefined behavior when handling some scenarios so fixing that should cover this kind of issues. I will close this bug and if you encounter this kind of issue again please re-open it or open a new issue.
