### ISSUE TITLE
Code Experts check rerunning unnecessarily

### ISSUE THREAD

**Issue by tresat** [linear-b/gitstream#108]
**Describe the bug**

The `codeExperts` filter keeps re-posting comments, despite no changes to the files in the PR.

**To Reproduce**

See the PR here: https://github.com/gradle/gradle/pull/24804.
The automation file is here: https://github.com/gradle/gradle/blob/386278ba2ea9e29597714ae3175bff4d7601ee6a/.cm/code_experts.cm

**Expected behavior**

The code experts comment should only have been added once.

**Comment by vim-zz** [comment]
@tresat It is fixed now. In case where multiple commits are pushed one after another, it can still happen that you'll see 2 comments, but every new commit will fix that.
