### ISSUE TITLE
Set required approvals blocking PR with 2 approvals

### ISSUE THREAD

**Issue by matthewparavati** [linear-b/gitstream#116]
**Describe the bug**

We have the set required approvals action run and set to 2. After a PR received 2 approvals, that check still showed as failed and waiting for 2 approvals so the PR was blocked from being merged

**To Reproduce**

Honestly, not entirely sure. We've seen this a couple of times before but not for a while. I thought it maybe had to do with our configuration before and maybe it does but raising it here in case it's a larger issue. 

The intermittent behavior of this makes it tough to know exactly why it occurred though 😕 

**Expected behavior**
After receiving 2 approvals, the set required approvals check passes and the PR can be merged by any dev

**Screenshots**

<img width="1066" alt="Screenshot 2023-04-20 at 16 08 30" src="https://user-images.githubusercontent.com/12176557/233477893-c9a12374-bca1-4c7d-a6d5-fe9d6e8260d5.png">

**Additional context**

**Comment by BenLloydPearson** [comment]
@matthewparavati welcome, and thanks for reporting this issue! We'll investigate it and let you know when we've implemented a solution for this. In the meantime, any other users who are affected by this bug can 👍  the original post or leave a comment to describe their situation.

**Comment by nunomluz** [comment]
We have just experienced something similar. The PR already has 3 approvals but `set-required-approvals` keeps asking for 3 more approvals.

**Comment by vim-zz** [comment]
Fixed @matthewparavati @nunomluz
