### ISSUE TITLE
The requested image's platform (linux/arm64/v8) does not match the detected host platform (linux/amd64)

### ISSUE THREAD

**Issue by yakirm-cr** [linear-b/gitstream#146]
**Describe the bug**

Workflow `gitStream workflow automation` constantly failing with the following error:
```log
Digest: sha256:8baef03339efdb3173827c39c343189516588f39d79eb4ce7c5a221942f7a4fb
Status: Downloaded newer image for gitstream/rules-engine:latest
docker.io/gitstream/rules-engine:latest
WARNING: The requested image's platform (linux/arm64/v8) does not match the detected host platform (linux/amd64) and no specific platform was requested
exec /usr/local/bin/npm: exec format error
Error: Process completed with exit code 1.
```

**To Reproduce**

1. Use the default gitstream workflow and .cm configuration as described [here](https://docs.gitstream.cm/github-installation/).
2. Open a new PR (or update an existing one).

**Expected behavior**

Workflow `gitStream workflow automation` should not fail with this error.

**Comment by vim-zz** [comment]
@yakirm-cr another a blip in the matrix (fixed)

**Comment by yakirm-cr** [comment]
@vim-zz 
Thanks for the quick response.
The issue is no longer reproducible. :slightly_smiling_face:
