### ISSUE TITLE
gitStream fails with: fatal: path '.cm/gitstream.cm' exists on disk, but not in 'master'

### ISSUE THREAD

**Issue by tresat** [linear-b/gitstream#173]
**Describe the bug**

gitStream had been working fine in our repo.  Today, a PR with no changes to gitStream configuration failed with an error saying: `fatal: path '.cm/gitstream.cm' exists on disk, but not in 'master'`.

**To Reproduce**

The PR that failed is here: https://github.com/gradle/gradle/pull/25054
The failing action output is here: https://github.com/gradle/gradle/actions/runs/5025879560/jobs/9013425600 

**Expected behavior**

gitStream shouldn't fail.

**Screenshots**

![image](https://github.com/linear-b/gitstream/assets/44197/40a2c48c-ba08-4124-ac05-49e4aea2b96c)

**Additional context**

Do you have any tips on how to troubleshoot failures like this?

**Comment by vim-zz** [comment]
Hi @tresat we are looking into this, and changed one of the configurations. Can you re-run gitStream on this PR? The easiest way is to do a new commit to the branch -- let me know if the issue still presists

**Comment by vim-zz** [comment]
@tresat we see you have more errors in your github action piepline, we are looking into it - i'll update

**Comment by vim-zz** [comment]
@tresat this PR you reported should now work, please re-run the check 
> re-run gitStream on this PR? The easiest way is to do a new commit to the branch or re-run using GitHub UI -- let me know if the issue still presists

The other issues you have in the action log, are because of PRs from forked repo, which is not supported right now - we are working on it and it will be availble soon

**Comment by tresat** [comment]
Now it reports "No automation applicable".

**Comment by vim-zz** [comment]
It means that the rule engine ran, but no automation was applicapable, do you expect any automation to yield any result?

**Comment by tresat** [comment]
Yes, I would have expected https://github.com/gradle/gradle/blob/master/.cm/change_categories.cm to generate some labels based on the files that were changed.

This PR has been merged, so it won't be changing further, but I will link additional examples here if they occur.

**Comment by vim-zz** [comment]
Got it. We fixed an issue based on your initial report, if you encounter issues again please open a new bug
