### ISSUE TITLE
Teams assigned as reviewers appear as `null` in `pr.reviewers` context:

### ISSUE THREAD

**Issue by groyoh** [linear-b/gitstream#186]
**Describe the bug**

When a team is assigned as reviewers, it will appear as `null` in `pr.reviewers`: 

```json
{
  "prContext": {
    "isFullyInstalled": true,
    "title": "Test with team reviewer",
    "approvals": [],
    "requested_changes": [],
    "author": "groyoh",
    "description": "",
    "checks": [],
    "created_at": "2023-05-24T06:38:42Z",
    "draft": false,
    "mergeable": true,
    "labels": [],
    "reviewers": [
      null
    ],
    "status": "open",
    "updated_at": "2023-05-24T06:43:20Z",
    "assignees": [],
    "contributors": [],
    "paths": [
      {
        "name": "gitstream.cm"
      }
    ],
    "author_teams": [
      "Gitstream bug report team 2"
    ],
    "comments": [],
    "reviews": [],
    "conversations": [],
    "isPrivate": false,
    "target": "main"
  }
}
```

**To Reproduce**

1. The `.cm` automation file: https://github.com/happydemics/gitstream-bug-report/blob/main/.cm/gitstream.cm 
2. The PR URL (as it contains the repo and PR identifiers): https://github.com/happydemics/gitstream-bug-report/pull/2
3. Add a team as reviewer

**Expected behavior**

The team name/id should appear in `pr.reviewers`.

**Comment by vim-zz** [comment]
@groyoh achievement unlocked! 2 bugs on the same day 😀

**Comment by vim-zz** [comment]
@groyoh it should work now
