### ISSUE TITLE
Add an `isCommentsChange` filter (similar to `isFormattingChange`)

### ISSUE THREAD

**Issue by tresat** [linear-b/gitstream#192]
**Is your feature request related to a problem? Please describe.**
I'd like to write automations that fire in the presence or absence of comments (including docstring comments like Javadoc).

**Describe the solution you'd like**
Just as the `isFormattingChange` allows automation to ignore less important changes, adding comments should be filterable in the same way, for similar reasons.

**Describe alternatives you've considered**
none

**Additional context**
Detecting various different types of comments would be helpful as well.  Some of the checks I'm imagining being useful:

- A new file has been added containing new types without any docstrings
- A class has changed significantly, but the class's docstring did not
- Large comment only should be routed towards a technical writer for review along with Docs only changes 

In certain cases, not doing these thing may be perfectly fine, but having gitStream put a reminder review comment on the PR "Did you forget to do X/Y/Z?" would be really helpful to get feedback to an author quicker.

**Comment by liamfd-titan** [comment]
Came here to suggest something like this - would be great. 

I've been considering whether it's feasible to do this with a regex like the ["Approve JavaScript Log Output Changes" entry in the pattern library](https://docs.gitstream.cm/automations/approve-javascript-log-output/).

**Comment by BenLloydPearson** [comment]
These are wonderful ideas, and I suspect gitStream might be capable of doing it in a manner similar to what @liamfd-titan suggests, particularly the first two ideas @tresat proposed. Related to this, we're working on opening up the possibility to create custom JavaScript "plugins" that would enable you to implement more complex filter functions like the `isFormattingChange` function on your own. 

In the meantime, I'll put some thought into this and see if we can produce something to the effect of what y'all are describing. If you have any specific PRs or other examples you can point to of places where rules like these would help that would be very helpful to us.

Also, if you manage to work up something of your own, we'd love to publish it and give you credit ;-)
https://github.com/linear-b/gitstream/issues/new?assignees=&labels=new-example&projects=&template=new_automation_example.md&title=New+Example%3A+

**Comment by BenLloydPearson** [comment]
@tresat @liamfd-titan I came up with a proposal for a handful of automations we could build that are specific to Javadoc. Lmk, what you think, and we'll work on these in the next week or so.

https://github.com/linear-b/gitstream/discussions/207

**Comment by BenLloydPearson** [comment]
@tresat @liamfd-titan We published these examples today: https://docs.gitstream.cm/integrations/javadoc/

I'm going to close this issue now, but feel free to re-open it if you run into any problems or think we should create additional examples or make changes to these examples.
