### ISSUE TITLE
Opened a PR and just got timeout after I followed the github installation guide 

### ISSUE THREAD

**Issue by aryeguy** [linear-b/gitstream#194]
**Describe the bug**

On https://github.com/diversionCompany/diversion/  branch: guy/route53-localhost-cognito

**To Reproduce**

1. The `.cm` automation file
2. The PR URL (as it contains the repo and PR identifiers)
3. Describe your PR relevant content 
4. Add relevant commit SHA

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by vim-zz** [comment]
@aryeguy the bus missing essential info, plese describe the problem you see and add more info

**Comment by vim-zz** [comment]
@aryeguy do you see gitStream in your Actions tab? if possible please share the log section of `Evaluate Rules`, or the error you see , here are the instructions: https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/using-workflow-run-logs#downloading-logs

<img width="814" alt="Screenshot 2023-05-30 at 17 49 00" src="https://github.com/linear-b/gitstream/assets/50141/b9d14433-91c8-472a-9781-2031858175f3">

**Comment by aryeguy** [comment]
Worked. Thanks
