### ISSUE TITLE
Estimated time to review respect linguist-generated 

### ISSUE THREAD

**Issue by liamfd-titan** [linear-b/gitstream#205]
**Is your feature request related to a problem? Please describe.**
The pull request estimated time to review labels are very useful, but it seems it tends to overestimate when there are large diffs for files that aren't typically reviewed. I've seen PRs with only a few lines of "real" file diffs that should probably have a "1 minute review" label being marked as 5-10 minute reviews as a result.

For a more concrete example - we generate a lot of TS from GraphQL schema files, and while we check these files in, they do not require review. We've set them to render like:

<img width="1150" alt="Screenshot 2023-06-06 at 13 49 09" src="https://github.com/linear-b/gitstream/assets/97480579/3c425643-acbf-4fad-8bc1-39c8c9ff91be">

So for us, since the files are intentionally not a required part of a review, ideally they would not be counted in the estimated review time.

Lockfiles (`yarn.lock` and `package-lock.json`) also show up this way, though I am not sure if gitstream is already handling those.

**Describe the solution you'd like**
Github allows you to use a `.gitattributes` file to specify file path globs that should be suppressed from review requests. See https://docs.github.com/en/repositories/working-with-files/managing-files/customizing-how-changed-files-appear-on-github for more. 

I think ideally the "estimated time to review" feature would respect this file, and ignore those lines. 

A few potential wrinkles:
* GH seems to do this by default for some files (e.g. `yarn.lock` and `package-lock.json`), so those might need to be taken into account.
* While `linguist-generated` is the only one mentioned in https://docs.github.com/en/repositories/working-with-files/managing-files/customizing-how-changed-files-appear-on-github, there are other [linguist options](https://github.com/github-linguist/linguist/blob/master/docs/overrides.md#summary) that might be worth taking into account.

**Describe alternatives you've considered**
* This could be opt in/out
* It could perhaps be built with a file filter in the cm file

**Additional context**
This feature is great!

**Comment by vim-zz** [comment]
@liamfd-titan are you looking for this? https://docs.gitstream.cm/cm-file/#configignore_files

**Comment by BenLloydPearson** [comment]
Ooh, @vim-zz beat me to it! To add some context, you would need to put your estimated time to review automation in its own file and add the `ignore_files` config directive to make sure that the ignore only applies to the time estimations, and not your other automations.

Let us know how this works for you

**Comment by liamfd-titan** [comment]
Oh, I missed that - looks great, thanks!
