### ISSUE TITLE
gitStream blocks merge on merge queue when it is defined as a required status check

### ISSUE THREAD

**Issue by yakirm-cr** [linear-b/gitstream#209]
**Describe the bug**

We enabled merge queue on one of repositories in the organisation and the [gitStream.cm](https://docs.gitstream.cm/github-installation/#configure-gitstream-to-block-merges) is defined as a required status check as part of the branch protection rules.
Merge queue runs are triggered via merge_group event as described [here](https://docs.github.com/en/enterprise-cloud@latest/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue#triggering-merge-group-checks-with-github-actions).
Unfortunately, as the gitStream.cm job is defined as required and it is NOT triggered as part of a merge_group event, the merge is not performed (removing the gitStream.cm from the list of required status checks resolves the issue).

**To Reproduce**

1. Configure gitStream as described [here](https://docs.gitstream.cm/github-installation/).
2. Add gitStream.cm as a required status check in the branch protection rules.
3. Open a new PR.

**Expected behavior**

gitStream.cm should be skipped for the merge_group event.

**Screenshots**

N/A

**Additional context**

N/A

**Comment by vim-zz** [comment]
@yakirm-cr to make sure I get it right, the merge queue involves another cycle after the PR is approved in which the CI checks are re-run and needs to pass in order to merge by the queue, right? 

Another question, what do you expect for the result:
1. Does gitStream check means anything in this stage, or should it just `pass`?
2. Are there any side effects from gitStream (actions) that you expect it to invoke?

**Comment by yakirm-cr** [comment]
> @yakirm-cr to make sure I get it right, the merge queue involves another cycle after the PR is approved in which the CI checks are re-run and needs to pass in order to merge by the queue, right?
> 

Yes.

> Another question, what do you expect for the result:
> 
> 1. Does gitStream check means anything in this stage, or should it just `pass`?

gitStream.cm is executed as part of the PR (as a required status check) before the PR is added to the merge queue.
If one of the required checks fail on gitStream.cm, it will not be allowed to be added to the merge queue.
So, once a PR is added to the merge queue, it means that gitStream.cm was successful (and, thus, at this pointin the merge queue it has no meaning - i.e. it should just pass). :slightly_smiling_face: 

> 2. Are there any side effects from gitStream (actions) that you expect it to invoke?

As part of the merge queue - no.

**Comment by vim-zz** [comment]
@yakirm-cr how urgent is it? does it prevent you from using gitStream?

**Comment by yakirm-cr** [comment]
@vim-zz 
At the moment, as a workaround we removed `gitStream.cm` from the list of required status checks (so, it does not block us from using it for most of our use cases).
However, we would definitely prefer to have it as a required status check. :slightly_smiling_face:

**Comment by vim-zz** [comment]
Ok, we'll support it

**Comment by yakirm-cr** [comment]
@vim-zz 
This is great! :slightly_smiling_face: 
I really appreciate it.

Thank you!

**Comment by PavelLinearB** [comment]
Hi @yakirm-cr 
We have changed the mechanism of the 'merge' action to fix the issue in case gitStream was marked as a required check.

Could you verify that this fix works for you?
Thanks!

**Comment by yakirm-cr** [comment]
@PavelLinearB 
Sure, I will check it and update. :slightly_smiling_face:

**Comment by yakirm-cr** [comment]
@vim-zz @PavelLinearB 
Unfortunately, after adding `gitstream.cm` as a required check, as part of a merge queue it is listed and nothing triggers the gitstream workflow for a new entry to the merge queue - which blocks the merge.
Am I missing anything?

**Comment by PavelLinearB** [comment]
Hi @yakirm-cr, Thanks for trying it.
There might be an issue with the merge_group event.
Would you mind having a short call with me? I'd like to see this event and get to the bottom of the issue.
My availability is visible [here](https://calendly.com/pavel-vaks/30min)

**Comment by PavelLinearB** [comment]
Hi @yakirm-cr, we have fixed this issue. now, in case gitStream Is a required check, it will no longer block merges using the merge queue.
Could you please verify this works on your end?
Thanks

**Comment by yakirm-cr** [comment]
@PavelLinearB 
Confirmed! :partying_face: 
The issue is resolved. :slightly_smiling_face:
