### ISSUE TITLE
Support reusing definitions across multiple automation files

### ISSUE THREAD

**Issue by tresat** [linear-b/gitstream#226]
**Is your feature request related to a problem? Please describe.**
We'd like to avoid copy-pasting the same snippets in multiple `.cm` files.  For instance, we have a list of devs grouped by team that is present in all our automations.  We also have a `CODEOWNERS`-ish division of the project into platform boundaries.

**Describe the solution you'd like**
Some sort of include or import functionality that would allow a section defined in one automation file to be referenced from multiple other files.  This could be as crude as a template system where a placeholder variable does text replacement using the contents of a referenced file in a sub-directory.

**Describe alternatives you've considered**
- Continuing to copy-paste and manually synchronize the block in multiple automation files.
- Writing a git pre-commit script to do this prior to every commit that touches the `.cm` directory.

**Comment by tresat** [comment]
If this something that would be possible with custom filter functions after they are available?  Could it be done with a Jinja template somehow?

**Comment by BenLloydPearson** [comment]
@tresat This is a fantastic idea! We would love to add this capability, but it would add quite a lot of complexity to how gitStream processes automations, and that would be a fairly significant effort to implement. We will be sure to provide updates here when we pursue this.

In the meantime, the best solution is to condense your automations into a single file where possible. This creates the risk of your CM files becoming more burdensome to update, but gitStream is designed to handle any number of automations in a single file.

**Comment by BenLloydPearson** [comment]
@tresat I'm happy to announce that we have a new feature that may solve this use case for you. We introduced the [env](https://docs.gitstream.cm/context-variables/#env) context variable that provides access to environment variables that are available to your GitHub Actions workflow for gitStream. I.e. you can add custom variables to your .github/workflows/gitstream.yml to store your user lists and access them in your automation.

Let me know if you have any questions, and feel free to re-open this if you continue to have issues.

**Comment by tresat** [comment]
I just gave this a try and unfortunately `env` [seems to be limited](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsenv) to a map of boolean, number or string types.  There's no way to supply arrays or nested objects.

When I try something like:

```
steps:
  - name: Evaluate Rules
    env:
      team1:
        - 'Tom'
        - 'Joe'
```

And then print out `{{ env.team1 }}` in a comment I just see `null`.

So this is only a partial solution for us - many of our potential use cases involve lists of values.  What would be most valuable is to have a list of values defined in `env` which we can then test against in our automations.  If we could define a list of authors in `gitstream.yml` and test in a `.cm` file if the current author is in that list, it would be very helpful.  We'd also like to define nested data structures that define properties about various directories in our build - I think doing this with arrays alone wouldn't be easy, we'd want custom nested objects for this.

Can you please re-open this?

**Comment by BenLloydPearson** [comment]
@tresat We had a conversation about this today and decided that this will be something we can support when we release custom JavaScript plugins early next year. I will provide any future updates here. Thanks!

**Comment by BenLloydPearson** [comment]
@tresat I'm happy to announce that gitStream now supports JavaScript plugins to build new filter functions that should solve this problem for you. [Here's the docs](https://docs.gitstream.cm/plugins/).

For example, we created an `isFlaggedUser` filter function that accomplishes something similar to what you're looking for: https://docs.gitstream.cm/filter-function-plugins/#isflaggeduser

If you have other ideas for plugins, or if you build some of your own, we would love to hear about it! You can [share your ideas here](https://github.com/linear-b/gitstream/discussions/categories/suggest-a-new-gitstream-plugin).
