### ISSUE TITLE
Getting a generic run fail that appears to be due to the PR being too big

### ISSUE THREAD

**Issue by kyle3s** [linear-b/gitstream#227]
**Describe the bug**

Our Gitstream actions fail after running for about 2 minutes on this specific PR. Judging by the 413 HTTP fail code, I'm guessing the PR is too large (completely fair, it is). Ideally, Gitstream would notify us of the fail reason somewhere so we don't have to check the logs.

![image](https://github.com/linear-b/gitstream/assets/90719100/6bca4904-3923-48f6-b4c9-8bf88ea4718e)

**Expected behavior**

When a PR is so big that it causes a service failure, a fail reason is given in the check notes.

**Additional context**

More of a "nice to have" than a true bug, feel free to handle it accordingly.

**Comment by BenLloydPearson** [comment]
Thanks for reporting this @kyle3s. We'll add this to our queue of potential issues to debug. Would you mind sharing info about how large the PR is so we can more accurately test this?

**Comment by PavelLinearB** [comment]
Hi @kyle3s 
Our team has recently implemented updates to our infrastructure to better support large files in pull requests.
Could you please confirm that this problem no longer persists on your end?

Thanks!

**Comment by kyle3s** [comment]
Hi Pavel,

In my case I haven't actually seen this error in quite a while because I
modified my gitstream.cm file to ignore the HTML snapshots that were
causing the issue and that fixed it.

Thanks,
Kyle

**Comment by PavelLinearB** [comment]
Oh, I see. Nice solution.
Anyway, as we have now added support for large files, I'm closing this issue. Please feel free to reopen it if this problem reoccurs.

Best,
Pavel.
