### ISSUE TITLE
Question: Can I block merging on an approved PR? 

### ISSUE THREAD

**Issue by matthewparavati** [linear-b/gitstream#242]
Scenario:

A PR has received approvals but for whatever reason, we don't want to merge it yet, so we add a label of "Do not merge".

----

Is there a gitstream action we can perform to block merging in this scenario? I see via the `pr` context that we can read the labels via `pr.labels` but I didn't see a way to block the merging even if we know that label has been added.

Also wondering if there's a way to force the gitstream check to fail in this scenario because that would block merge for us.

---

This might be a feature request but I figured I'd ask as a question first in case there's a way to accomplish it already and I've just missed it 😅

**Comment by vim-zz** [comment]
How about using [require-reviewers](https://docs.gitstream.cm/automation-actions/#require-reviewers)?

**Comment by matthewparavati** [comment]
> How about using [require-reviewers](https://docs.gitstream.cm/automation-actions/#require-reviewers)?

@vim-zz Thanks for the reply, I'll take a look at that and see if I can get it to work!

**Comment by matthewparavati** [comment]
@vim-zz This worked, thank you! Not surprisingly, the one caveat is the required reviewer(s) should not have already approved the PR or the merging won't get blocked. Work around for us is to assign our manager who rarely is requested/approves PRs so this shouldn't be an issue.

It looks like the current behavior is to not assign the required reviewer to the PR(which is fine for our purposes). So this action will be silent and not alert them to the review?

Once the `also_assign` arg is released, we'll just need to set that to false to continue having the above behavior?
