### ISSUE TITLE
gitStream workflow automation execution warnings in GitHub

### ISSUE THREAD

**Issue by yakirm-cr** [linear-b/gitstream#314]
**Describe the bug**

We started to notice the warnings in the execution of the gitStream workflow automation in GitHub (refer to screenshot below).

**To Reproduce**

1. Trigger the execution of the `gitStream workflow automation` (via new PR, update an existing PR, etc).

**Expected behavior**

The execution of the `gitStream workflow automation` is successful without any warnings.

**Screenshots**

![image](https://github.com/linear-b/gitstream/assets/86773995/4b99b348-df2a-47a5-a6e9-e7f54cac2cba)

**Additional context**

We are using the same `gitstream.yml` provided [here](https://docs.gitstream.cm/github-installation/).

**Comment by BenLloydPearson** [comment]
Thanks for reporting this @yakirm-cr I let our product team know about this, and they are looking into it. Some fixes that might resolve this have already been pushed. Are you still encountering this problem?

**Comment by yakirm-cr** [comment]
> Thanks for reporting this @yakirm-cr I let our product team know about this, and they are looking into it. Some fixes that might resolve this have already been pushed. Are you still encountering this problem?

Unfortunately, yes.

**Comment by yakirm-cr** [comment]
Looks like the issue is no longer reproducible.
Closing.
