### ISSUE TITLE
Trouble with Gitlab installation

### ISSUE THREAD

**Issue by josh-s-g** [linear-b/gitstream#321]
I have followed the instructions for installing gitStream with Gitlab here: https://linearb.helpdocs.io/article/0xxpvue4s9-connect-git-stream-using-a-git-lab-integration including
- creating a `cm` project (repo) in the Gitlab group containing other projects with the `.gitlab-ci.yml` file in the project root ([this file](https://docs.gitstream.cm/downloads/gitlab-ci.yml)) and the gitstream.cm rules file ([this file](https://docs.gitstream.cm/downloads/gitstream.cm))
-  connecting gitStream (Settings -> Git -> click Connect gitStream) in LinearB
<img width="394" alt="image" src="https://github.com/linear-b/gitstream/assets/9271916/b1e32375-21c8-49c1-83d9-b9b2ab44491b">

- I have connected Gitlab and LinearB together with my own account (I am the group and project `Owner`) for now, to test.

According to this instructions that's it, but when a new merge request is opened, nothing gitStream-related happens. Should I expect to see a pipeline job execute in the `cm` repo at least?

I'm struggling to find where to debug the issue, any pointers would be most appreciated, thanks!

**Comment by BenLloydPearson** [comment]
Thanks @josh-s-g we'll look into this and get back to you.

**Comment by BenLloydPearson** [comment]
I'm closing this issue since there hasn't been a response in multiple weeks. If this is still a problem, please reopen this issue and let us know. Thanks!

**Comment by josh-s-g** [comment]
I spoke to @PavelLinearB and he suggested to make sure the `cm` repo is using shared (public) gitlab runners (ours were private). Unfortunately this didn't resolve this issue. I'm still a little in dark about how to go about diagnosing or debugging the problem

**Comment by vim-zz** [comment]
@josh-s-g I am re-opening this issue. Can you share the pipeline job log you see when using shared runner?

**Comment by josh-s-g** [comment]
Thanks - no pipeline jobs are triggered in the `cm` repo when a merge request is opened in one of the repos that gitstream is enabled for

**Comment by vim-zz** [comment]
@josh-s-g how is gitStream installed? is it using LinearB integration? https://linearb.helpdocs.io/article/0xxpvue4s9-connect-git-stream-using-a-git-lab-integration

**Comment by josh-s-g** [comment]
That's right, those are the instructions I followed: Connected gitStream in LinearB settings, created the `cm` repo with the `.yml` and `.cm` rules file

**Comment by vim-zz** [comment]
gitStream for GitLab is available for LinearB customers, please send the issue to support@linearb.io and include screenshots of the setup you have.

**Comment by vuer** [comment]
Hey, I tried to contact support but they do not reply. Can u help me with that?
