### ISSUE TITLE
Support running gitstream (real + dry run) on draft PRs

### ISSUE THREAD

**Issue by michaeldrotar** [linear-b/gitstream#33]
**Is your feature request related to a problem? Please describe.**
We always open our PRs in draft to make sure _all_ checks pass. Since gitstream will be one of these checks, it'll cause frustration for our flow if we have to get all other checks (unit tests, builds, etc) to pass separately and then might need to handle any gitstream failures after marking it ready for review, which is the same point reviewers then get assigned but might do reviews _before_ the gitstream fixes are then made.

Additionally when testing new gitstream changes, if the review has to be marked ready for review then reviewers will be assigned while we're actively working on making changes to .cm files to test things out in dry run mode. So this should also work from a Draft PR.

**Describe the solution you'd like**
Have gitstream run as normal for Draft PRs too rather than skipping itself.

**Describe alternatives you've considered**
We could change our process but I think there are clear downsides to that and friction with people reviewing things that aren't finished yet.

**Additional context**
Having it as a setting would be fine if there's a reason someone wouldn't want it to run on drafts.
As-is, it's also a little confusing that there's a `{{ pr.draft }}` variable since it'll never run when that's true - and that seems like a perfect use case to instead always run gitstream but allow each automation to do `if: {{ not pr.draft }}` if it doesn't want something to run on a draft

**Comment by admarko** [comment]
+1

**Comment by akotek** [comment]
+1

**Comment by liamfd-titan** [comment]
Interesting that the docs say you can choose to let it run on draft PRs on https://docs.gitstream.cm/how-it-works/:

<img width="870" alt="Screenshot 2023-05-26 at 16 25 35" src="https://github.com/linear-b/gitstream/assets/97480579/f2167377-3875-4298-a5e5-9594d8739105">

But the link is dead, it goes to https://docs.gitstream.cm/how-it-works/cm-file/

**Comment by PavelLinearB** [comment]
Hi @michaeldrotar , @admarko , @liamfd-titan 
We have recently added the [explicit triggers](https://docs.gitstream.cm/execution-model/#explicit-triggers) functionality to gitStream.
Explicit triggers invoke the gitStream action regardless of the status of the PR.
