### ISSUE TITLE
Add wildcard/regex for ignore_repositories

### ISSUE THREAD

**Issue by PFarrell90** [linear-b/gitstream#377]
**Is your feature request related to a problem? Please describe.**
I would like a feature that allows wildcard and/or regex values for the `ignore_repositories` option in `config:` so that we don't need to continually update rules when repos are created.

**Describe the solution you'd like**
When managing hundreds of repo's for an org, separating their name by a prefix/suffix for team/tool/department etc. makes organizing them easier. It would be great if we could dynamically assign rules based on a wildcard or regex syntax 

i.e., `Team1-Repo1` and `Repo1-Team2` -- we want to build a rule that would only apply to everything under `Team1-` but not `Team2`. 

It looks like wildcards are available for filenames, but not repositories: https://docs.gitstream.cm/cm-file/#configignore_repositories

**Describe alternatives you've considered**
Presently, it looks like our only option is to add each named repo as a per-line string in a rule's `config:ignore_repositories` sub-section. While precise, this isn't elegant and is a bit of a chore.

Thank you,

**Comment by BenLloydPearson** [comment]
Thanks for the recommendation @PFarrell90, this is a great idea! We'll provide updates here on the status of this improvement.

**Comment by PavelLinearB** [comment]
Hi
We have recently added this capability to gitStream, documentation is available [here](http://127.0.0.1:8000/cm-file/#configignore_repositories)

I am closing this issue; please re-open it in case you find it does not work as expected
