### ISSUE TITLE
GitStream workflow is failing for all open PRs

### ISSUE THREAD

**Issue by yakirm-cr** [linear-b/gitstream#390]
**Describe the bug**

GitStream workflow started failing today (no changes were done in gitstream workflow or rules) with the following errors (for all open PRs):

```
Digest: sha256:199eea9c6ae82d6f0f703d566bf32064e0945aea7568108b0a3974cb84b14baf
Status: Downloaded newer image for gitstream/rules-engine:latest
docker.io/gitstream/rules-engine:latest

> gitstream-rules-engine@1.0.0 start
> node src/app.js

/node_modules/@linearb/gitstream-core/dist/gitstream-core.cjs.development.js:25
var fetch = _interopDefault(require('node-fetch'));
                            ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /node_modules/node-fetch/src/index.js from /node_modules/@linearb/gitstream-core/dist/gitstream-core.cjs.development.js not supported.
Instead change the require of index.js in /node_modules/@linearb/gitstream-core/dist/gitstream-core.cjs.development.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/node_modules/@linearb/gitstream-core/dist/gitstream-core.cjs.development.js:25:29)
    at Object.<anonymous> (/node_modules/@linearb/gitstream-core/dist/index.js:7:20)
    at async Promise.all (index 0) {
  code: 'ERR_REQUIRE_ESM'
}
Error: Process completed with exit code 1.
```

**To Reproduce**

1. Configure gitStream as described [here](https://docs.gitstream.cm/github-installation/).
2. Add gitStream.cm as a required status check in the branch protection rules.
3. Open a new PR (or update an existing one).
4. GitStream workflow is executed automatically.

**Expected behavior**

GitStream workflow is executed successfully and rules are processed successfully.

**Screenshots**

N/A

**Additional context**

N/A

**Comment by SallyBlichG** [comment]
Same here, [opened an issue](https://github.com/linear-b/gitstream-github-action/issues/55) in the github action repo as well

**Comment by yakirm-cr** [comment]
@vim-zz @PavelLinearB 
Could you, please, check and advise?

**Comment by vim-zz** [comment]
We identified the issue and are working on a fix

**Comment by vim-zz** [comment]
The issue was resolved, it was caused due to wrong tag being released, once we noticed that (thanks you for opening this issue) the tag was updated. The issue should now be resolved.

**Comment by yakirm-cr** [comment]
@vim-zz 
Confirmed - the issue is no longer reproducible.
Thanks for the prompt response! :slightly_smiling_face:
