### ISSUE TITLE
gitstream fails with error - "Failed to get PR context"

### ISSUE THREAD

**Issue by AnkurAgarwal-ST** [linear-b/gitstream#4]
**Describe the bug**

It is noticed the that sometimes gitstream fails with error **_"Failed to get PR context"_**. I have seen this error on 2 PRs so far. 
Please note that this is not always happening.

PRs URL for reference - 
https://github.com/Hodes-Inc/Auth_0/pull/123
https://github.com/Hodes-Inc/Auth_0/pull/120

**To Reproduce**

Raise a PR, and wait for the gitstream check to execute.
The gitstream check fails sometimes.
Attaching gitstream.cm file for reference. _The extension of the file is changed to .txt as GitHub was not allowing to upload of a .cm file._
[gitstream.txt](https://github.com/linear-b/gitstream/files/10292426/gitstream.txt)

**Expected behavior**

Gitstream checks should execute without failing its execution. It may fail if a rule fails but should not fail even to execute it.

**Screenshots**
![image](https://user-images.githubusercontent.com/89902473/209282547-cf840aee-c0ec-46b2-9538-c99acb3c0e27.png)

![image](https://user-images.githubusercontent.com/89902473/209281373-a61b7038-0b83-4acd-a47e-ef99822832b2.png)
![image](https://user-images.githubusercontent.com/89902473/209281389-f9a00ef7-c462-465f-8f73-edb389432134.png)

**Additional context**

N/A

**Comment by vim-zz** [comment]
We are looking at this @AnkurAgarwal-ST 👀

**Comment by ShakedZrihen** [comment]
Hi @AnkurAgarwal-ST 
we found the bug and deployed a fix for that :)
please try again and let me know if all good now !

Shaked.

**Comment by AnkurAgarwal-ST** [comment]
I am happy to close this, for now, I will raise an issue again if we face a similar problem again.

**Comment by damianhxy** [comment]
I am facing a similar issue

PR: https://github.com/autolab/Autolab/pull/1675
gitstream.cm: https://github.com/autolab/Autolab/blob/master/.cm/gitstream.cm
Action: https://github.com/autolab/Autolab/actions/runs/3809993530/jobs/6481770874
