### ISSUE TITLE
Reuse automations for few projects

### ISSUE THREAD

**Issue by julijaciric** [linear-b/gitstream#410]
Hi, thanks for creating this project! Very much appreciated by me and the team!

**Is your feature request related to a problem? Please describe.**
Currently gitstream is used by one team in the big organization. We want to avoid creating organization rules and want to reuse gitstream automations only on few projects. We don't want to affect other teams with our gitstream automations.

**Describe the solution you'd like**
We would like to have a possibility to import workflow from the other repository with automation rules.

**Describe alternatives you've considered**
Currently we are copy/pasting .cm directory to multiple projects.

**Comment by PavelLinearB** [comment]
Hey @julijaciric, Thanks for reaching out, Your enthusiasm for gitstream is very much appreciated! 

This is indeed a valuable enhancement, which is on our radar, and planned for H1 2024.
I'd love to chat with you more about our planned design. Can we sync up in the next few weeks to get your thoughts about it?
Thanks,
Pavel.

**Comment by julijaciric** [comment]
Hi @PavelLinearB thank you for your fast response, and yes I am available to chat!

**Comment by IvanRibakov** [comment]
Hi @PavelLinearB, are there any updates on this issue? Is it still going to hit the H1 deadline?

**Comment by PavelLinearB** [comment]
Hi @IvanRibakov. Thanks for reaching out.
We have increased the granularity of the triggering mechanism by adding support for including or excluding branches and repositories using strings or regexes. [Docs are available here](https://docs.gitstream.cm/execution-model/#triggers-section)
This will allow you to create better org-level rules without affecting other branches/repositories. More information is available in the [docs](https://docs.gitstream.cm/cm-file/#organization-automation-rules)
