### ISSUE TITLE
Add explicit trigger for pr ready for review

### ISSUE THREAD

**Issue by julijaciric** [linear-b/gitstream#446]
**Is your feature request related to a problem? Please describe.**

We create PRs in the state of draft first, and then we move them into ready for review. We don't want to assign reviewers until PR is ready. And we don't want to assign them multiple times.

Following GitStream [documentation](https://docs.gitstream.cm/execution-model/#explicit-triggers-syntax) and [more](https://docs.gitstream.cm/context-variables/#pr), there is no trigger for **pr_ready_for_review**.

**Describe the solution you'd like**
Have a pr_ready_for_review trigger

**Describe alternatives you've considered**
on:
 pr_created     
if:
       - {{ not pr.draft }}

**Comment by BenLloydPearson** [comment]
Hi @julijaciric thanks for reporting your issue!

I don't quite understand why the `{{ not pr.draft }}` statement doesn't work for you. Would you mind providing more detail about what the gap in expectations vs. functionality here is? That would help us understand your problem better.

Something else to consider: you can use labels to trigger gitStream. So, you could set your automation to trigger if someone adds a "Ready for review" label, for example. We also have some examples that use slash commands inside GitHub comments to trigger gitStream. Let me know if you have questions about this.

**Comment by julijaciric** [comment]
Hi @BenLloydPearson, sorry for the late reply. We already had a call with Pavel, but to answer your question:

- We need an assignment when pr is not in the draft state, so don't assign when pr is created but in a draft state.

Can you please give me more details about label? I can test that approach 

> Hi @julijaciric thanks for reporting your issue!
> 
> I don't quite understand why the `{{ not pr.draft }}` statement doesn't work for you. Would you mind providing more detail about what the gap in expectations vs. functionality here is? That would help us understand your problem better.
> 
> Something else to consider: you can use labels to trigger gitStream. So, you could set your automation to trigger if someone adds a "Ready for review" label, for example. We also have some examples that use slash commands inside GitHub comments to trigger gitStream. Let me know if you have questions about this.

**Comment by julijaciric** [comment]
Hi @BenLloydPearson  @PavelLinearB 
Are there any updates?
Can you please provide more details how to add label when Pr is Ready to review?

**Comment by PavelLinearB** [comment]
Hey @julijaciric 
Great timing for the follow-up! We have just added this capability, along with a few more triggers. [Documentation will be available soon](https://docs.gitstream.cm/execution-model/#explicit-triggers)
