### ISSUE TITLE
Automation rules are triggered multiple times in a single run

### ISSUE THREAD

**Issue by raunakkathuria** [linear-b/gitstream#447]
**Describe the bug**
The gitStream rule is adding multiple comments for the same rule in a single run

![image](https://github.com/linear-b/gitstream/assets/2534747/07b7187a-e9f0-4651-8542-910a985c6187)

**To Reproduce**

1. The `.cm` automation file is https://github.com/deriv-com/test-gitstream/blob/master/.cm/gitstream.cm
  
  Repo folder structure
  
![image](https://github.com/linear-b/gitstream/assets/2534747/0bdb4c3e-2c05-48e1-bfce-f81f63973cd5)

2. PR: https://github.com/deriv-com/test-gitstream/pull/2
3. Just testing it to evaluate gitStream for our organization

**Expected behavior**

It should have commented once during a single run but every time it executes the rule and comments twice at the same time, expected it to comment only once

**Screenshots**

GitHub actions
![image](https://github.com/linear-b/gitstream/assets/2534747/fc22d2e4-adf3-4072-a2dc-f2794a9fbb47)
![image](https://github.com/linear-b/gitstream/assets/2534747/a0950ab0-6661-4233-b755-e8b773b27aae)

**Additional context**

I have checked the previous issues raised and following the suggestions mentioned in those, for example https://github.com/linear-b/gitstream/issues/197

**Comment by vim-zz** [comment]
@raunakkathuria can you try to refresh the page and see if this is still the case?

**Comment by raunakkathuria** [comment]
> @raunakkathuria can you try to refresh the page and see if this is still the case?

Yes, still the same 
![image](https://github.com/linear-b/gitstream/assets/2534747/6aab42ef-b21a-46e0-9668-bad896fd963a)

**Comment by raunakkathuria** [comment]
Also, I made the repo public, you can check now https://github.com/deriv-com/test-gitstream/pull/2

**Comment by vim-zz** [comment]
Thank you @raunakkathuria for pointing this out. The issue likely stems from gitStream receiving closely timed events from the GitHub API, leading to multiple outputs. Rest assured, each output is still processed and validated by our rule engine. We're working on a fix to better handle such scenarios and improve gitStream's handling of sequential API events. Your feedback is greatly appreciated!

**Comment by raunakkathuria** [comment]
@vim-zz Thanks for the prompt response and looking into it. Looking forward for a fix

**Comment by vim-zz** [comment]
Hi @raunakkathuria a fix was applied, can verify on your end?

**Comment by vim-zz** [comment]
@raunakkathuria I am closing this, if you see it happens again, please re-open
