### ISSUE TITLE
gitStream workflow is failing

### ISSUE THREAD

**Issue by yakirm-cr** [linear-b/gitstream#61]
**Describe the bug**

gitStream is failing for all PRs with the following error:

![image](https://user-images.githubusercontent.com/86773995/226416230-ad0c76f5-6342-4c63-bcec-2b35318610db.png)

**To Reproduce**

1. Open a PR in a repository with the default `.github/workflows/gitstream.yml` and `.cm/gitstream.cm`

**Expected behavior**

gitStream workflow should pass. :slightly_smiling_face:

**Comment by yakirm-cr** [comment]
We are also experiencing the same issue reported in #62 in all of our PRs.
Unfortunately, we had to remove the gitStream from the list of required status checks - it blocks merging of PRs. :slightly_frowning_face:

**Comment by yeelali14** [comment]
@matthewparavati @yakirm-cr We deployed a fix for this issue, can you please confirm all is OK from your side? 
Thank you!

**Comment by yakirm-cr** [comment]
@yeelali14 thanks!
I see it working again in multiple PRs for us. :slightly_smiling_face:

**Comment by yeelali14** [comment]
@yakirm-cr Awesome! thank you for checking 🙏
