### ISSUE TITLE
Gitstream action spins indefinitely when the job fails + multi-line values don't indent

### ISSUE THREAD

**Issue by michaeldrotar** [linear-b/gitstream#62]
**Describe the bug**

(This should probably be 2 bugs but I have an example that shows both)

If the job fails, such as from a syntax error in the generated yaml file, it never reports back to the PR's actions that it failed and the icon stays spinning indefinitely (10d and counting here)
![image](https://user-images.githubusercontent.com/820263/226440358-d4e51218-5051-4afe-ba36-0b8e1fceb691.png)

**To Reproduce**

There are a number of ways to reproduce this, I usually hit it when some of the dynamic content causes the error like with a multi-line description

1. Create an automation like so
```yaml
  print_description:
    if:
      - true
    run:
      - action: add-comment@v1
        args:
          comment: |
            description: {{ pr.description }}
```
2. Set a single-line description, it should work
3. Set a multi-line description like this
```
Line 1

Line 2
```
4. You get an error like this:
```
2023-03-10T00:33:54.4061491Z /node_modules/js-yaml/lib/loader.js:187
2023-03-10T00:33:54.4061837Z   throw generateError(state, message);
2023-03-10T00:33:54.4062092Z   ^
2023-03-10T00:33:54.4099659Z YAMLException: end of the stream or a document separator is expected (50:1)
2023-03-10T00:33:54.4099950Z 
2023-03-10T00:33:54.4100698Z  48 |             description: Line 1 ...
2023-03-10T00:33:54.4100948Z  49 | 
2023-03-10T00:33:54.4101422Z  50 | Line 2 ...
```

**Expected behavior**

1. It should indent each line in the generated output
```
48 |             description: Line 1 ...
49 | 
50 |             Line 2 ...
```
2. If it does fail for any reason, it should report back to stop the spinner (I've had other failures from dynamic data but this is the easiest to demonstrate)

**Screenshots**

Included above.

**Additional context**

I had a slack chat with Ofer about this but recording it here too since the infinite spinner failure has come up a few times now that we have devs using it.

**Comment by vim-zz** [comment]
@michaeldrotar this should work now

**Comment by admarko** [comment]
@vim-zz - we believe this is still happening

**Comment by vim-zz** [comment]
@admarko, I'm not totally certain about the details of what you're seeing, but we're actively developing a failsafe mechanism that will address all of these situations. It's our top priority.

**Comment by vim-zz** [comment]
The failsafe mechanism is active now

**Comment by admarko** [comment]
Thank you @vim-zz!
