### ISSUE TITLE
Accessing Github Actions Variables from Gitstream

### ISSUE THREAD

**Issue by torynet** [linear-b/gitstream#69]
I'm not sure if this is a feature request or just a documentation request. I'm hoping it's already possible and I just need to know how.

**Is your feature request related to a problem? Please describe.**
As much as I would love GitHub "team reviews" to work well, they just don't. If I want to just get two reviews from any of my seven team members, I can add the team to the PR and require two reviewers. Great, but the first person from that team that reviews, will eliminate the team from the requested reviewers, and the PR will stop showing up in requested reviews for all of the members. So, I need an option where I can just assign all the people from the team individually and require two reviews, but then not have to store their actual names in the .cm file because that sucks.

**Describe the solution you'd like**
I would like to access Github Actions Variables from within GitStream, such that I can store useful configuration in a place that exists outside of the source. Then I can just put a list of reviewers in one of those variables, and use it as the source of reviewers for GitStream.

**Describe alternatives you've considered**
The only other thing I can think to do, is make a number of Git Team (like 10) and add all of them. Then if team members change, you could just change who is in those teams. That really sucks though. That might be worse than usernames in the source.

**Additional context**
Here is a screen shot of what this might look like in Github Action Variables.

![image](https://user-images.githubusercontent.com/959980/227663214-8713b4af-f6e2-4fb8-a57a-9ae73812d8fe.png)

**Comment by torynet** [comment]
I was hoping to just be able to utilize `${{ CODE_REVIEWERS }}` like you do in native Github Actions, but it doesn't seem to work.

**Comment by vim-zz** [comment]
@torynet

**Comment by torynet** [comment]
They would see the PR in their "Review Requested" list, but when utilizing a "team" for review, it will disappear from all of their lists, once one person reviews.

**Comment by torynet** [comment]
I take it there is currently no way to access Github action variables?

**Comment by torynet** [comment]
@vim-zz Is there any indication if this is possible currently, or would require an enhancement to GitStream?

**Comment by BenLloydPearson** [comment]
@torynet  I'm happy to announce that we have a new feature that may solve this use case for you. We introduced the [env](https://docs.gitstream.cm/context-variables/#env) context variable that provides access to environment variables that are available to your GitHub Actions workflow for gitStream. I.e. you can add custom variables to your .github/workflows/gitstream.yml to store your user lists and access them in your automation.

Let me know if you have questions, and feel free to re-open this issue if you continue to have problems.
