### ISSUE TITLE
Single quote in last name breaking gitstream?

### ISSUE THREAD

**Issue by nikolasleblanc** [linear-b/gitstream#73]
**Describe the bug**

`/bin/sh: syntax error: unterminated quoted string` failures are being seen consistently by a user with a single quote in his last name, which exists in the payload being provided to the docker image. 

Could it be that there's some escaping required that isn't happening?

**To Reproduce**

1. Submit a PR to a gitstream enabled repo or mimic in a shell with a payload that includes an author with a `'` in the last name

**Expected behavior**

Gitstream works as expected

**Screenshots**

<img width="588" alt="image" src="https://user-images.githubusercontent.com/1944954/228370515-644a52e5-1a28-4ee3-bd3b-90ceba09e7ca.png">

**Comment by BenLloydPearson** [comment]
Hi @nikolasleblanc :wave: thanks for reporting this and for your patience with us while we look into this issue. We've confirmed this bug exists and have added it to our backlog, but unfortunately, we can't estimate when we'll be able to address this problem. We'll provide updates on the status of this bug in this thread.

Any other users who have encountered this bug, please give a :+1: to the original post to help us better understand how to prioritize this issue.

Thanks again!

**Comment by yakirm-cr** [comment]
@BenLloydPearson 
We are facing a similar issue when the commit message contains single quote marks:
```log
SyntaxError: Bad control character in string literal in JSON at position 5452
    at JSON.parse (<anonymous>)
    at file:///src/app.js:16:15
    at ModuleJob.run (node:internal/modules/esm/module_job:192:25)
```

In our case the commit message was:
```
Replace calls to 'pip3' with 'pip'
```

Amending the commit message to be without the single quote marks resolved the issue:
```
Replace calls to pip3 with pip
```

**Comment by cbchenoweth** [comment]
adding my +1 to this on behalf of my org.  And just wanted to give a little extra information for our scenario that might help expose another thing to consider for how this can blocks users in an enterprise org (@BenLloydPearson - just thought you might want to get another scenario / more context for prioritization and such).

We are using [Enterprise Managed Users](https://docs.github.com/en/enterprise-cloud@latest/admin/identity-and-access-management/using-enterprise-managed-users-for-iam/about-enterprise-managed-users), so the users display name is not even managed directly in GitHub, it comes from our IdP provider.  (so really annoying to try and update and manage users names "just for github/gitstream to handle the name")

**Comment by PavelLinearB** [comment]
Hi @nikolasleblanc , @yakirm-cr  and @cbchenoweth
We have solved this issue, and now gitStream supports all types of quotes and ticks in the username, branch name, pr title, and comments.

I am closing this issue. Feel free to reopen or reach out in case it reoccurs.
