### ISSUE TITLE
Ability for gitstream to ignore github actions

### ISSUE THREAD

**Issue by DanielleSparks** [linear-b/gitstream#76]
**Is your feature request related to a problem? Please describe.**
We have built a github action to automatically merge the main branch into any open PR's to keep PR's up to date. When this action runs, the gitstream automations are run again which prompts email notifications from github as well as to the Slack channel we setup for notifications. This could happen many times on an open PR before it is tested/merged so we have temporarily disabled the gitstream actions to avoid the excessive notifications until a solution is found.

**Describe the solution you'd like**
A way to prevent the gitstream actions from running when a github action (workflow) makes a change to the PR.

**Describe alternatives you've considered**
We have tried to define the workflow to prevent gitStream actions from running but have been unsuccessful. 

**Additional context**

**Comment by BenLloydPearson** [comment]
Hi @DanielleSparks We have released a new capability called explicit triggers which enables you to specific when gitStream should run, and I believe this should solve your use case. For example, you could configure gitStream to only run when the PR is created or when a new commit is created. 

More details here: https://docs.gitstream.cm/execution-model/#explicit-triggers

Let me know if this works for you, or if you still need something different for your use case.
