### ISSUE TITLE
`calc` is not documented

### ISSUE THREAD

**Issue by kevcube** [linear-b/gitstream#86]
**Describe the bug**

I can't find any documentation explaining what the `calc` object that is used in `calc.etr` is, or what other properties it contains. I'm only able to assume that ETR is "estimated time (to) review" but I can't find that in documentation anywhere either. Maybe I'm missing something obvious! 😅

**Comment by vim-zz** [comment]
@kevcube `calc` is an _accessory sections_. These sections are user defined, can contain common variables and expressions that you can use to simplify your automation rule syntax and reuse it in different rules within the same file. This can help make your automation rules more readable and maintainable.

You can read more here: https://docs.gitstream.cm/cm-syntax/
