### ISSUE TITLE
Gitstream fails with `fatal: bad revision` but the check never completes

### ISSUE THREAD

**Issue by matthewparavati** [linear-b/gitstream#89]
**Describe the bug**

Gitstream fails with `fatal: bad revision` but the check never completes and stays in the running/in progress state.

**To Reproduce**
Create a `fatal: bad revision` error

**Expected behavior**
If a `fatal: bad revision` error occurs, the gitstream check fails

**Screenshots**
<img width="386" alt="Screenshot 2023-04-11 at 07 08 25" src="https://user-images.githubusercontent.com/12176557/231142833-98d84e03-77c6-4d62-868c-6ed13082cff9.png">

**Additional context**
```
Error: {"message":" \n Git command failed. reason: Command failed: cd repo && git diff sc-52094/25-message-details-total-revenue-card'...'marketing-overview-file-refactor' -- .cm/*.cm\nfatal: bad revision 'sc-52094/25-message-details-total-revenue-card...marketing-overview-file-refactor'\n"}

Error: Process completed with exit code 67.
```

### Add any other context about the problem here.
Just some questions about this bad revision error, and it might be silly but 
- is there a best way to avoid this when it seems fine locally and in github but then gitstream is throwing the error?
- it _seems_ to mostly (maybe only) occur when a feature branch is pointing at another feature branch, rather than develop
  - it still seems to occur on these PRs even after the base automatically changes to develop

Feel free to close this if it will be covered by #62 - seems like it might be but wanted to make sure and also ask my questions about the bad revision error in case I can get some clarity on it

**Comment by vim-zz** [comment]
A fail-safe mechanism is implemented and should prevent this. Under the hood what happens here is:
